[book]
authors = ["Miguel Raz Guzmán Macedo"]
language = "en"
multilingual = false
src = "src"
title = "teaching-material2"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.print]
enable = true    # include support for printable output
page-break = true # insert page-break after each chapter

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 1         # the depth to start folding

[output.html.playground]
editable = true         # allows editing the source code
copyable = true          # include the copy button for copying code snippets
copy-js = true           # includes the JavaScript for the code editor
line-numbers = true     # displays line numbers for editable code
runnable = true          # displays a run button for rust code

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

